### ISSUE TITLE
Просьба к авторам.

### ISSUE THREAD

**Issue by betcher** [AktivCo/rutoken-linux-gui-manager#1]
Здравствуйте. Делаю скрипт который собирает модуль для рутокена для нового проекта аля МагОС. Модуль собирается в чруте, окружение ограничено (иксов нет). От скрипта нужно установить все зависимости которые могут вашим утилитам понадобиться. Сейчас  сделано так. Клонируется эта гит репа и из utils.sh запускается пару функций.  
cd /usr/share/rutoken/2fa-tuner-lib/
sed -i 's/wget\ *-q/wget /' ./utils.sh 
. utils.sh
init
install_common_packages

Сегодня пришлось этот кусочек исправлять, потому что пропала функция  install_сommon_packages. Исправил на install_packages и вроде заработало, но боюсь что вы снова можете что-то поменять. 
Можете добавить скрипт, который без zenity и tkinter окошек, консольно установит зависимости и завершится?

**Comment by lo1ol** [comment]
Добрый день.

До недавно решили оставить единую функцию установки пакетов, чтобы упростить структуру поставки пакетов. Постараемся в дальнейшем больше не менять из структуры

По поводу работы с утилитой без иксов. В либе есть специальная функция init_gui_manager, которая позволяет выбирать какой графический менеджер использовать. Можно выбрать dialog (он же вроде не требует иксов) и полноценно работать с утилитой. В дальнейшем постараемся сделать автоматический подходящего гуи менеджера

По поводу МагОС возможно не все так будет просто насчет установки пактов и различных настройщиков т.к. утилита напрямую не испытывалась на ней.  Если есть возможность, можете создать вою реализацию для своей системы на основе наиболее подходящей существующей из папки implementation.

Постараемся в ближайшее время добавить поддержку МагОС, но если успеете это все сделать быстрее нас, то будем благодарны за pull request

**Comment by Mironenko** [comment]
> Сегодня пришлось этот кусочек исправлять, потому что пропала функция install_сommon_packages. Исправил на install_packages и вроде заработало, но боюсь что вы снова можете что-то поменять.

@betcher, что вам мешает брать конкретную версию зависимости, а не master?

**Comment by betcher** [comment]
Система основана на пакетной базе Роса. И ваши утилиты работают, то есть ничего менять не нужно. Если в функции которые подтягивают зависимости изменений не планируется, то вопрос снят. Имею ввиду в utils.sh, а не те что под конкретные дистры.

**Comment by betcher** [comment]
@Mironenko, не совсем понял. Предлагаете зафиксировать коммит? Возможно так и сделаю позже, сейчас мне кажется  активно пилится. Еще совсем недавно на сайте рутокена была ссылка на гит похожей утилиты на dialog, потом она исчезла вместе с гитом и появился этот проект наверное еще не устаканились :)
Спасибо за оперативные ответы.

**Comment by Mironenko** [comment]
> @Mironenko, не совсем понял. Предлагаете зафиксировать коммит? Возможно так и сделаю позже, сейчас мне кажется активно пилится.

Это лично мое мнение, не хочу вам его навязывать: поскольку проект активно пилится, вероятность, что в его реализации изменится что-то, на что вы заложились, высока. Засчет фиксации коммита вы будете управлять зависимостями, а не они (в те моменты, когда опять придется чинить что-то поломавшееся) вами.

В то же самое время, стек, через который работает Рутокен в Linux меняется редко. Не рассматривали варианта забирать необходимые вам файлы напрямую, без использования внутренних функций скрипта utils.sh?

**Comment by betcher** [comment]
У меня собирается два модуля для рутокена. В одном из них только либа PKCS, во втором эта утилита и все что ей нужно в том числе и либа. Использовать можно зависмо от потребностей любой модуль. То есть все что нужно для токенов изначально есть в сборке и речь о доустановке пакетов специфичных именно для этой утилиты. Там ткинтер3, fakerpm еще что-то, именно к работе токена отношение не имеющее.  
К сожалению не уверен что могу подробно распространяться о сборке, подписал бумагу. Основана на идеях Магос и репозиториях Роса. 
Чтобы ваша утилита работала в оригинальном Магос достаточно в case где чек дистра на основе os-release добавить к *"ROSA"* еще *"MagOS"*. 
Ос-релиз магос выглядит так:
NAME="MagOS Linux 2016"
VERSION="2016"
ID=rosa
VERSION_ID=2016
PRETTY_NAME="MagOS Linux"
ANSI_COLOR="1;34"
HOME_URL="http://www.magos-linux.ru/"
BUG_REPORT_URL="http://www.magos-linux.ru/"

**Comment by lo1ol** [comment]
> Чтобы ваша утилита работала в оригинальном Магос достаточно в case где чек дистра на основе os-release добавить к _"ROSA"_ еще _"MagOS"_.

Если это изменение единственное которое нужно, для того, чтобы все завелось, то в ближайшее время добавим его.

Решение с установкой гуи менеджера решает вашу проблему с иксами?

**Comment by betcher** [comment]
Нет, dialog не подходит.  Скрипт должен отработать полностью автоматом. Если изменений не планируется хотя-бы в названии функций init и install_packages, то проблем у меня быть не должно.

**Comment by betcher** [comment]
> Если это изменение единственное которое нужно, для того, чтобы все завелось, то в ближайшее время добавим его.

Для магос - достаточно.
