### ISSUE TITLE
Зачем на Росе пакеты rpmdevtools и lib64p11-devel?

### ISSUE THREAD

**Issue by mikhailnov** [AktivCo/rutoken-linux-gui-manager#3]
Здравствуйте!
Опакечиваю эти скрипты в RPM-пакет в репозиторий Росы, возник вопрос: зачем в списке устанавливаемых пакетов rpmdevtools и lib64p11-devel?

Поискал используемые утилиты из rpmdevtools:
$ rpm -ql rpmdevtools | grep bin/ | awk -F'/' '{print $NF}' | sort -u | while read -r line ; do grep -inHr "$line" ; done
Ничего не нашлось.

**Comment by lo1ol** [comment]
вероятно и правда лишние. Возможно раньше использовались какие-то из зависимостей этих пакетов
