### ISSUE TITLE
Качественная иконка в SVG

### ISSUE THREAD

**Issue by mikhailnov** [AktivCo/rutoken-linux-gui-manager#4]
При опакечивании этой утилиты надо сделать desktop-файл, а для него нужна нормальная иконка. Нашел только такую: https://dev.rutoken.ru/download/attachments/557059/PUB?version=6&modificationDate=1586955473000&api=v2

Желательно бы логотип Рутокена в SVG с указанием лицензии на его распространение или просто какую-то иконку, ее можно и в находящийся в этом репозитории desktop-файл прописать.

**Comment by mikhailnov** [comment]
Пока так:
![2022-04-13_07-20](https://user-images.githubusercontent.com/15802528/163102972-f7af4e21-0099-4db2-97e6-7bd1eb8f383b.png)

Пакет: https://abf.io/import/rutoken-linux-gui-manager (предварительная версия)
https://abf-downloads.rosalinux.ru/rosa2021.1/repository/x86_64/contrib/release/rutoken-linux-gui-manager-0-0.gite7683f.956657.2-rosa2021.1.noarch.rpm

Нерешенные проблемы в соседних тикетах описал.

**Comment by PavelAnfimov** [comment]
Логотип Рутокен есть в пресс-ките: https://www.rutoken.ru/press-center/kit/. Посмотрите, пожалуйста, насколько он вам подойдет.

**Comment by lo1ol** [comment]
Предлагаю взять иконцу с нашего другого продукта ["Панель управления Рутокен"](https://play-lh.googleusercontent.com/j9qS8p5UcctekAyqsXQKqlBg08L2HHYysbhpTxoDBziCZZ8NNXkHFExGPWH7vRC6vfw)

**Comment by PavelAnfimov** [comment]
> Предлагаю взять иконцу с нашего другого продукта ["Панель управления Рутокен"](https://play-lh.googleusercontent.com/j9qS8p5UcctekAyqsXQKqlBg08L2HHYysbhpTxoDBziCZZ8NNXkHFExGPWH7vRC6vfw)

Эта иконка в формате SVG: https://owncloud.aktiv-company.ru/owncloud/s/dA3ohayaqd5pPuY
