### ISSUE TITLE
Работа без librtpkcs11ecp.so

### ISSUE THREAD

**Issue by mikhailnov** [AktivCo/rutoken-linux-gui-manager#5]
Задокументируйте, пожалуйста, может ли эта штука работать без блобятины librtpkcs11ecp.so

Я вот такое вижу:
![image](https://user-images.githubusercontent.com/15802528/163096670-fe96e4ab-293e-483f-ae6a-8b596a03024d.png)

Непонятно, сможет ли оно прожить без нее или нет. Рутокена сейчас под рукой нет.

**Comment by mikhailnov** [comment]
Судя по коду типа `pam_pkcs11_insert="NR == 2 {print \"auth sufficient pam_pkcs11.so pkcs11_module=$LIBRTPKCS11ECP\" } {print}"` - не сможет Для сертифицированных ОС блобятина не подходит. Вообще не понятно толком, для чего эта блобятина нужна. Если только для ГОСТа, то было бы очень хорошо, чтоб этот GUI мог работать без блобятины, т.к. она не подходит для сертифицированных ОС, да и вообще для репозитория.

**Comment by PavelAnfimov** [comment]
pkcs11ecp -- это часть СКЗИ Рутокен ЭЦП 2.0. Библиотека нужна для взаимодействия с Рутокеном, в том числе для работы с криптоядром.

**Comment by lo1ol** [comment]
Утилита для общения с токеном использует эту pkcs11 библиотеку. pam модуль для разблокировки тоже использует его. 

Как один из способов не использовать нашу библиотеку -- это настроить двухфакторную аутентификацию с RSA парой, предварительно отформатировав токен с помощью библиотеки opensc-pkcs11.

Но это уже нужно будет делать вручную. Подробнее об этом можно почитать (здесь)[https://github.com/OpenSC/pam_pkcs11]
